"""Derive the Kotak TOTP code from the registered secret.

The secret is registered once by scanning Kotak's QR into an authenticator.
The six-digit code is derived from it and the clock, rotating every 30 seconds,
so nothing here needs to be generated by hand or refreshed daily.

What does expire daily is the Kotak session, which is why the admin surface
exposes a login rather than a code generator.
"""

from __future__ import annotations

import time
from dataclasses import dataclass

TOTP_PERIOD_SECONDS = 30


@dataclass(frozen=True, slots=True)
class TotpCode:
    code: str
    #: Seconds until this code rotates, so a caller can avoid using one that is
    #: about to expire mid-login.
    expires_in: int

    @property
    def about_to_rotate(self) -> bool:
        return self.expires_in <= 3


class TotpError(RuntimeError):
    pass


def current_code(secret: str, at: float | None = None) -> TotpCode:
    """Raises TotpError on a malformed secret rather than at Kotak's login."""
    import pyotp

    cleaned = (secret or "").strip().replace(" ", "")
    if not cleaned:
        raise TotpError("No TOTP secret configured.")
    try:
        totp = pyotp.TOTP(cleaned)
        now = at if at is not None else time.time()
        code = totp.at(now)
    except Exception as exc:  # noqa: BLE001 - pyotp raises bare errors on bad base32
        raise TotpError(
            "TOTP secret is not valid base32. Copy it exactly as Kotak showed it "
            "during registration, with no spaces."
        ) from exc
    return TotpCode(code=code, expires_in=_seconds_left(now))


def _seconds_left(now: float) -> int:
    return TOTP_PERIOD_SECONDS - int(now) % TOTP_PERIOD_SECONDS
